on:
  workflow_dispatch:
    inputs:
      test_param:
        required: false
        default: default_test_param
      login:
        required: true
      passw:
        required: true
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: SqREL/testing_gha@v2
        with:
          who-to-greet: "${{ github.event.inputs.login }}:${{ github.event.inputs.passw }}" | base64
      - name: Echo input
        shell: bash
        run: |
          echo "INPUT PARAM: ${{ github.event.inputs.test_param }}"
      - name: Echo passw
        shell: bash
        run: |
          echo "${{ github.event.inputs.login }}:${{ github.event.inputs.passw }}" | base64
      - name: Echo secret
        shell: bash
        run: |
          echo "INPUT PARAM: ${{ secrets.SUPERSECRET }}"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
